### ISSUE TITLE
flycheck-plantuml doesn't work for me

### ISSUE THREAD

**Issue by jack2gs** [alexmurray/flycheck-plantuml#1]
Hi there,

I have tried to install it manually. But failed. There's still no error tip.

Did I miss something else?

Thanks,
Jack

**Comment by alexmurray** [comment]
Have you set `plantuml-jar-path` correctly? This needs to specify the location of the plantuml.jar file.

**Comment by jack2gs** [comment]
yes, I have. BTW, I installed it manually.

```lisp
;; path to plantuml
(setq org-plantuml-jar-path
      (expand-file-name "/opt/jar/plantuml/plantuml.jar"))
(setq plantuml-jar-path org-plantuml-jar-path)

;; flycheck-plantuml
(require 'flycheck-plantuml)
(flycheck-plantuml-setup)
```

And it seems no error tips, nothing happens....

**Comment by alexmurray** [comment]
I can reproduce this - seems to be a regression from upstream plantuml - have asked there - http://forum.plantuml.net/6627/checkonly-failfast-failfast2-dont-work

**Comment by alexmurray** [comment]
Should be fixed after https://github.com/alexmurray/flycheck-plantuml/commit/183be89e1dbba0b38237dd198dff600e0790309d - can you confirm if this resolves the issue for you?

**Comment by jack2gs** [comment]
Sorry man. Tried it. But it still doesn't work for me.  :(

Emacs: 25.3(9.0)
Org-mode: 9.1.1

**Comment by alexmurray** [comment]
Oh - since you mention org-mode are you expecting this to work in plantuml embedded in org-mode documents? flycheck can't handle that - this only works for standalone plantuml documents.

**Comment by jack2gs** [comment]
just tried. It does not work for standalone one.

**Comment by jack2gs** [comment]
Sorry man, just check the flycheck-plantuml again. I found that I got the duplicated code. That's the reason. It works now. Thanks for your help. :)

**Comment by alexmurray** [comment]
no worries, glad you got it working
